quarkus:
  banner:
    path: banner.txt
  flyway:
    enabled: false
  datasource:
    db-kind: postgresql
    username: ${E_BUDGET_DB_USERNAME:postgres}
    password: ${E_BUDGET_DB_PASSWORD:postgres}
    jdbc:
      url: jdbc:postgresql://${E_BUDGET_DB_HOSTNAME:localhost}:${E_BUDGET_DB_PORT:5432}/${E_BUDGET_DB_NAME:ebudget}

"%test":
  quarkus:
    flyway:
      enabled: true
      migrate-at-start: true
      locations: filesystem:../e-budget-db/src/main/resources/db/migration
    datasource:
      devservices:
        enabled: true
        image-name: postgres:latest
        username: postgres
        password: postgres
        db-name: ebudget_test
        port: 5433
      jdbc:
        url: jdbc:postgresql://localhost:5433/ebudget_test