services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ebudget
    ports:
      - "5432:5432"
    volumes:
      - ./ebudget-data:/var/lib/postgresql/data
    restart: always
