name: Continuous Integration
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: e-Budget/e-budget-be/.github/actions/setup@main
      - uses: e-Budget/e-budget-be/.github/actions/cache-sonar@main
      - uses: e-Budget/e-budget-be/.github/actions/cache-maven@main
      - uses: e-Budget/e-budget-be/.github/actions/build@main
        with:
          sonarToken: ${{ secrets.SONAR_TOKEN }}
